##==============================================
# Application Context Path
# ==============================================
server: 
  servlet.context-path: /WBA
  port : 8082
##==============================================
# Basic Authentication Configuration
# ==============================================
wbauser: wbauser
wbapass: wbapass

##==============================================
# Azure Cosmos Database Configuration
# ==============================================
azure :
    cosmosdb : 
          uri : https://localhost:8081
          key : C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==
          database : mysqlapicosmos
##==============================================
# Kafka Configuration
# ==============================================
spring : 
    kafka:
      consumer:
        group-id: group_id
      bootstrap-servers : 127.0.0.1:9092
##==============================================
# End point Configurations
# ==============================================
api-endpoint-config:
    user : /hello
    phRateAsync: /getPhRateAsync
    phRate : /getPhRate
    phRateException : /getPhRateException
    saveProduct : /saveProduct
    saveProducts : /saveProducts
    deleteProductById : /deleteProductById
    updateProduct : /updateProduct
    listAllProducts : /listAllProducts
    findProductById : /findProductById
    findByMedName : /findByMedName
    fetchMedName: /fetchMedName
    testCache: /testCache